[env]
# Additional Compiler Versions
GHC_VERSION = "9.14.1"

[tools]
# Compilers with Semantic Versioning
go     = "1.24.13"
julia  = "1.13.1"
nim    = "2.2.12"
node   = "26.10.0"
python = "3.13.16"
rust   = "1.99.0"
zig    = "0.16.0"

# Compilers with Date-Based Versioning
odin = { version = "dev-2026-09", strip_components = 1, bin_path = "." }

# Compiler Bootstrappers
ghcup = "0.2.6.2"

# Formatters with Semantic Versioning
clang-format = "23.1.2"
ormolu       = "0.9.0.0"
ruff         = "0.16.10"

# Formatters with Date-Based Versioning
ols = "dev-2026-08"

# Formatters from Conda
"conda:fprettify" = "0.3.7"

[settings]
disable_hints = ["*"]
