name: Test

on:
  push:
    branches:
      - 'master'

permissions:
  contents: write

env:
  BUILD_TYPE: Release

jobs:
  build-linux-shared_x86-64:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Build the Programs
        run: make

      - name: Run the Tests
        working-directory: build
        run: make test

      - name: Upload Coverage Reports
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
