name: Test

on:
  push:
    branches:
      - 'master'

permissions:
  contents: write

jobs:
  test_linux_x86-64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Build the Programs
        run: make

      - name: Run the Tests
        run: make test
