name: Test

on:
  push:
    branches:
      - 'master'

permissions:
  contents: write

jobs:
  test:
    name: ${{matrix.os}}
    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    env:
      MISE_DATA_DIR: ${{github.workspace}}/.mise

      MISE_CACHE_DIR: ${{github.workspace}}/.mise/cache
      MISE_STATE_DIR: ${{github.workspace}}/.mise/state

    steps:
      - uses: actions/checkout@v7

      - uses: jdx/mise-action@v5
        env:
          TEMP: ${{runner.temp}}

      - name: Setup the Environment
        run: make setup ${{runner.os == 'Windows' && 'ghcup/bin/ghc' || '.ghcup/bin/ghc'}}

      - name: Build the Programs
        run: make

      - name: Run the Tests
        run: make test
