name: Test

on:
  push:
    branches:
      - 'master'

permissions:
  contents: write

jobs:
  test_linux_x86-64:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install Necessary Packages
        run: sudo snap install zig

      - name: Build the Programs
        run: make

      - name: Run the Tests
        run: make test

      - name: Upload Coverage Reports
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
