name: Test

on:
  push:
    branches:
      - 'master'

permissions:
  contents: write

jobs:
  test_linux_x86-64:
    runs-on: ubuntu-latest

    env:
      MISE_DATA_DIR: ${{github.workspace}}/.mise

      MISE_CACHE_DIR: ${{github.workspace}}/.mise/cache
      MISE_STATE_DIR: ${{github.workspace}}/.mise/state

    steps:
      - uses: actions/checkout@v7

      - uses: jdx/mise-action@v5

      - name: Build the Programs
        run: make

      - name: Run the Tests
        run: make test
